FROM fedora:33

ENV DEBIAN_FRONTEND=noninteractive

RUN dnf -y install \
    python3.9 \
    python3.9-devel \
    python3.9-pip \
    rpm-build \
    && dnf clean all

COPY requirements.txt .

RUN pip3 install --upgrade pip \
    && pip3 install pyinstaller \
    && pip3 install -r requirements.txt \
    && pip3 install "python-xlib>=0.33,<1.0"

WORKDIR /app
COPY . .

CMD ["/bin/bash"]